server : 
  port : 8500
#logging:
#  file: ./springboot.log
spring: 
  application:   
    name: merge_manage 
  datasource: 
      url: jdbc:mysql://${mysql.host}:${mysql.port}/merge?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true&useSSL=false
      username: ${mysql.username}
      password: ${mysql.password}
      driverClassName: com.mysql.jdbc.Driver     
  thymeleaf : 
    cache : false 
  data: 
    mongodb: 
      uri: mongodb://root:123456@127.0.0.1:27017/merge
      connectTimeout: 300000
      maxWaitMillis: 300000
  #mvc:
    #static-path-pattern: classpath:/static/**

ftp: 
  address: ${ftp.address}
  port: ${ftp.port}
  username: ${ftp.username}
  password: ${ftp.password}
  path: ${ftp.path}

mybatis: 
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

    